[workspace]
members = [
    "error-code",
    "error-code-derive"
]

resolver = "3"

[workspace.dependencies]
error-code = {path = "./error-code"}
error-code-derive = { path = "./error-code-derive"}
anyhow = "1.0.99"
thiserror = "2.0.12"
http = "1.0.0"
